version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: employeemanager
    volumes:
      - mysqlVolume:/var/lib/mysql
    networks:
      employeeManagerNetwork:

  employeeManager:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    image: ltmartin/employeemanager:latest
    container_name: employeemanager
    ports:
      - "8080:8080"
    networks:
      employeeManagerNetwork:
    depends_on:
      - db
    links:
      - db

volumes:
  mysqlVolume:

networks:
  employeeManagerNetwork: